# These are supported funding model platforms

github: BuxOrg
custom: https://gobitcoinsv.com/?utm_source=github&utm_medium=sponsor-link&utm_campaign=bux-server&utm_term=bux-server&utm_content=bux-server
