auth:
    admin_key: xpub661MyMwAqRbcFrBJbKwBGCB7d3fr2SaAuXGM95BA62X41m6eW2ehRQGW4xLi9wkEXUGnQZYxVVj4PxXnyrLk7jdqvBAs1Qq9gf6ykMvjR7J
    require_signing: false
    scheme: xpub
    signing_disabled: true
cache:
    cluster:
        coordinator: memory
        prefix: bux_cluster_
        redis: null
    engine: freecache
    # Prefixed with "_", because it's unused by default
    _redis:
        dependency_mode: true
        max_active_connections: 0
        max_connection_lifetime: 1m0s
        max_idle_connections: 10
        max_idle_timeout: 10s
        url: redis://localhost:6379
        use_tls: false
db:
    datastore:
        debug: false
        engine: sqlite
        table_prefix: xapi
    # Prefixed with "_", because it's unused by default
    _mongodb:
        database_name: xapi
        debug: false
        max_connection_idle_time: 0s
        max_connection_time: 0s
        max_idle_connections: 0
        max_open_connections: 0
        table_prefix: ""
        transactions: false
        uri: mongodb://localhost:27017/xapi
    # Prefixed with "_", because it's unused by default
    _sql:
        debug: false
        driver: postgresql
        host: localhost
        max_connection_idle_time: 0s
        max_connection_time: 0s
        max_idle_connections: 0
        max_open_connections: 0
        name: xapi
        password: ""
        port: "5432"
        replica: false
        skip_initialize_with_version: true
        table_prefix: ""
        time_zone: UTC
        tx_timeout: 10s
        user: postgres
    sqlite:
        database_path: ./bux.db
        debug: false
        max_connection_idle_time: 0s
        max_connection_time: 0s
        max_idle_connections: 0
        max_open_connections: 0
        shared: true
        table_prefix: ""
debug: true
debug_profiling: true
disable_itc: true
# Prefixed with "_", because it's unused by default
graphql:
    enabled: false
import_block_headers: ""
# Prefixed with "_", because it's unused by default
_monitor:
    auth_token: ""
    bux_agent_url: ws://localhost:8000/websocket
    debug: false
    enabled: false
    false_positive_rate: 0.01
    load_monitored_destinations: false
    max_number_of_destinations: 100000
    monitor_days: 7
    processor_type: bloom
    save_transaction_destinations: true
# Prefixed with "_", because it's unused by default
_new_relic:
    domain_name: domain.com
    enabled: false
    license_key: BOGUS-LICENSE-KEY-1234567890987654321234
nodes:
    broadcast_client_apis: []
    minercraft_api: mAPI
    minercraft_custom_apis: []
    use_mapi_fee_quotes: true
# Prefixed with "_", because it's unused by default
_notifications:
    enabled: false
    webhook_endpoint: ""
paymail:
    # Prefixed with "_", because it's unused by default
    _beef:
        pulse_auth_token: mQZQ6WmxURxWz5ch
        pulse_url: http://localhost:8080/api/v1/chain/merkleroot/verify
        use_beef: false
    default_from_paymail: from@domain.com
    default_note: bux Address Resolution
    domain_validation_enabled: true
    domains:
        - localhost
    enabled: true
    sender_validation_enabled: true
request_logging: true
server:
    idle_timeout: 1m0s
    port: "3003"
    read_timeout: 15s
    write_timeout: 15s
task_manager:
    factory: memory
