version: "3.9"
services:
  server:
    build: .
    environment:
      - BUX_ENVIRONMENT=development
    ports:
      - "3003:30003"
    volumes:
      - ./config:/config:Z
    links:
      - redis
      - db
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_NAME=bux
      - POSTGRES_USER=bux
      - POSTGRES_PASSWORD=postgres

