version: "3.9"
services:
  server:
    build: .
    environment:
      - BUX_ENVIRONMENT=development
    ports:
      - "3003:3003"
    volumes:
      - ./config:/config:Z
    links:
      - redis
      - db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_NAME=bux
      - POSTGRES_USER=bux
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 5s
      retries: 3
