---
name: "On pull request"

on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - opened

permissions:
  pull-requests: write

jobs:
  on-pr:
    uses: bactions/workflows/.github/workflows/on-pull-request.yml@main
