name: Release to Container Registry
permissions:
  contents: write
  packages: write

env:
  GO111MODULE: on

on:
  push:
    tags:
      - 'v*'

jobs:
  release_default:
    uses: bactions/workflows/.github/workflows/release-go-server.yml@tmp/use-custom-release-config
    with:
      version: ${{ github.ref_name }}
      os: linux
      cgo_enabled: true
      release_binaries: false
      docker_registry: ghcr.io
      release_goreleaser_config: ./release/.goreleaser-linux.yml
    secrets:
      GH_PAT: ${{ secrets.PAT }}

